### PR TITLE
Clean up the Solarwinds DPA dockerfile

### PR DESCRIPTION
**Pull request by rlnrln**
- move version string to VERSION and VERSION_ environment variables
- download the installer file by executing wget instead of using the ADD statement
- run the installer with the --silent-install and --install-dir flags during Docker image creation instead of during container startup. This allows for adding the {repo,system,server}.properties files via a volume (ie docker run -v /config/solarwinds/dpa:/app/dpa_10_2_579/iwc/tomcat/ignite_config/idc -p 8123:8123 my/solarwinds-dpa:latest)
- Use a new start.sh script as entrypoint.

### CODE REVIEW

**Comment by leecalcote** [comment]
@rlnrln thanks! We're taking a look...

**Comment by hernandanielg** [comment]
This version works like a charm! 

This fixes #9

I had to add the following step 
```
+RUN chmod +x /start.sh
```

Because it was throwing permission errors
```
➜  dpa git:(dpa-dockerfile) docker run -d solarwinds/dpa                                                                                                       
08e42ddd63a3f157239b2c72a89a0349c81636082e7dee38a0f4982e34ec2851                                                                                               
docker: Error response from daemon: oci runtime error: container_linux.go:262:starting container process caused "exec: \"/start.sh\": permission denied".
```
@rlnrln great job!

**Comment by leecalcote** [comment]
@hernandanielg thanks for validating this PR.

**Comment by rlnrln** [comment]
No need to RUN chmod +x, just setting the executable bit on the file in git should do the trick.

**Comment by leecalcote** [comment]
LGTM. Thank you, @rlnrln for this updates! and to @hernandanielg for confirming!

**Pull request merged**
